# Generated by Django 3.1.3 on 2021-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_title',
            field=models.CharField(max_length=100),
        ),
    ]
