# Generated by Django 3.1.3 on 2020-12-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201205_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='product_id',
        ),
    ]
